UPDATE `world`.`creature_template` SET `name`='竞技场观察师', `subname`='DSWOW' WHERE `entry`='190003';
UPDATE `world`.`creature_template` SET `name`='竞技场3v3单排', `subname`='DSWOW' WHERE `entry`='190004';
UPDATE `world`.`creature_template` SET `name`='附魔大师', `subname`='DSWOW' WHERE `entry`='190006';
UPDATE `world`.`creature_template` SET `name`='宠物大师', `subname`='DSWOW' WHERE `entry`='190005';
UPDATE `world`.`creature_template` SET `name`='工会头头', `subname`='DSWOW' WHERE `entry`='190007';
UPDATE `world`.`creature_template` SET `name`='玩家工具', `subname`='DSWOW' WHERE `entry`='190009';
UPDATE `world`.`creature_template` SET `name`='传送员', `subname`='DSWOW' WHERE `entry`='190012';
UPDATE `world`.`creature_template` SET `name`='初始装备NPC', `subname`='DSWOW' WHERE `entry`='190013';
UPDATE `world`.`creature_template` SET `name`='专业NPC', `subname`='DSWOW' WHERE `entry`='190010';
UPDATE `world`.`creature_template` SET `name`='PVP头衔', `subname`='DSWOW' WHERE `entry`='190014';
UPDATE `world`.`creature_template` SET `name`='幻化商', `subname`='DSWOW' WHERE `entry`='190015';
UPDATE `world`.`creature_template` SET `name`='幻化师', `subname`='DSWOW' WHERE `entry`='190016';
UPDATE `world`.`creature_template` SET `name`='韩国整容所', `subname`='DSWOW' WHERE `entry`='190008';
UPDATE `world`.`creature_template` SET `name`='重构师', `subname`='DSWOW' WHERE `entry`='190011';
UPDATE `world`.`creature_template` SET `subname`='DSWOW' WHERE `entry`='700001';
UPDATE `world`.`creature_template` SET `subname`='DSWOW' WHERE `entry`='700002';
UPDATE `world`.`creature_template` SET `subname`='DSWOW' WHERE `entry`='700004';
UPDATE `world`.`creature_template` SET `subname`='DSWOW' WHERE `entry`='700005';
UPDATE `world`.`creature_template` SET `subname`='DSWOW' WHERE `entry`='700006';
UPDATE `world`.`creature_template` SET `subname`='DSWOW' WHERE `entry`='95025';
UPDATE `world`.`creature_template` SET `subname`='DSWOW' WHERE `entry`='95026';
UPDATE `world`.`creature_template` SET `subname`='DSWOW' WHERE `entry`='95027';
UPDATE `world`.`creature_template` SET `subname`='DSWOW' WHERE `entry`='95028';
UPDATE `world`.`creature_template` SET `subname`='DSWOW' WHERE `entry`='190001';
UPDATE `world`.`creature_template` SET `subname`='DSWOW' WHERE `entry`='190002';
UPDATE `world`.`creature_template` SET `name`='死亡骑士' WHERE `entry`='95015';
UPDATE `world`.`creature_template` SET `name`='德鲁伊' WHERE `entry`='95016';
UPDATE `world`.`creature_template` SET `name`='猎人' WHERE `entry`='95017';
UPDATE `world`.`creature_template` SET `name`='法师' WHERE `entry`='95018';
UPDATE `world`.`creature_template` SET `name`='圣骑士' WHERE `entry`='95019';
UPDATE `world`.`creature_template` SET `name`='牧师' WHERE `entry`='95020';
UPDATE `world`.`creature_template` SET `name`='盗贼' WHERE `entry`='95021';
UPDATE `world`.`creature_template` SET `name`='萨满' WHERE `entry`='95022';
UPDATE `world`.`creature_template` SET `name`='术士' WHERE `entry`='95023';
UPDATE `world`.`creature_template` SET `type_flags`='0' WHERE `entry`>='190001'
